[package]
name = "polkadot_indexer"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "1.0", features = ["derive"] }  # For JSON parsing
serde_json = "1.0"  # Handle JSON data
tungstenite = "0.17"  # WebSocket client
tokio = { version = "1", features = ["full"] }  # Async runtime
url = "2.2"
RUST_BACKTRACE=1 
