[package]
name = "polkadot_indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] } 
subxt = "0.29" 
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1.0"
futures-util = "0.3" 